services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.aiostreams.rule=Host(`${DOMAIN_NAME}`)'
      - 'traefik.http.routers.aiostreams.entrypoints=websecure'
      - 'traefik.http.routers.aiostreams.tls.certresolver=letsencrypt'
    volumes:
      - ./data:/app/data